name: xp_ui
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/action_icons/close_icon.png
    - assets/action_icons/maximize_icon.png
    - assets/action_icons/maximized_icon.png
    - assets/action_icons/minimize_icon.png
    - assets/action_icons/help_icon.png

  fonts:
    - family: Trebuchet
      fonts:
        - asset: fonts/Trebuchet.ttf
        - asset: fonts/Trebuchet-Italic.ttf
          style: italic
    - family: MS
      fonts:
        - asset: fonts/micross.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
