name: xp_ui
description: "A collection of Flutter widgets that faithfully replicate the iconic visual style of Windows XP. Easy to integrate to give your apps a unique retro tap."
version: 0.1.0
repository: https://github.com/jessimalak/xp_ui

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inset_shadow: ^2.0.3
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/action_icons/
    - assets/explorer_icons/
    - assets/system_icons/

  fonts:
    - family: Trebuchet
      fonts:
        - asset: fonts/Trebuchet.ttf
        - asset: fonts/Trebuchet-Italic.ttf
          style: italic
    - family: MS
      fonts:
        - asset: fonts/micross.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
